pipeline {
    agent any
    
    environment {
        // 1. Windows Docker Desktop Fixes
        DOCKER_HOST = 'tcp://host.docker.internal:2375'
        DOCKER_TLS_VERIFY = ''
        
        // 2. App Image Variables
        DOCKER_IMAGE = "chaos-app"
        DOCKER_TAG = "v${env.BUILD_NUMBER}" 
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from Git...'
            }
        }

        stage('Security Scan') {
            steps {
                echo 'Scanning for Noisy Neighbors...'
                sh '''
                    if [ -f "project-1/manifests/deployment.yaml" ]; then
                        echo "File exists, checking vital signs..."
                        grep -q "kind: Deployment" project-1/manifests/deployment.yaml && \
                        grep -q "image:" project-1/manifests/deployment.yaml && \
                        echo "YAML Structure looks valid for deployment."
                    else
                        echo "Error: deployment.yaml not found!"
                        exit 1
                    fi
                '''
            }
        }

        stage('Build Image') {
            steps {
                echo "Building Docker Image..."
                // Using the dynamic DOCKER_TAG variable defined above
                sh "docker build --no-cache -t ${DOCKER_IMAGE}:${DOCKER_TAG} project-1/"
            }
        }

        stage('Deploy to K8s') {
            steps {
                echo "Deploying to Local Cluster..."
                withCredentials([string(credentialsId: 'k8s-token', variable: 'K8S_TOKEN')]) {
                    sh """
                        kubectl apply -f project-1/manifests/deployment.yaml \
                        --server=https://host.docker.internal:54150 \
                        --token="${K8S_TOKEN}" \
                        --insecure-skip-tls-verify=true \
                        --validate=false
                    """
                }
            }
        }

        stage('Run Playwright Tests') {
            steps {
        // Pull the fresh test suite code
                checkout scm
        // Install dependencies and run tests natively on the Jenkins agent
                sh 'npm install'
                sh 'npx playwright test'
            }
        }
    }
}
