pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "chaos-app"
        DOCKER_TAG = "v${env.BUILD_NUMBER}" // Incremental versioning!
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code from Git...'
                // Jenkins handles this automatically if pointed at a repo
            }
        }

        stage('Security Scan') {
            steps {
                echo 'Scanning for Noisy Neighbors...'
                // SRE Move: Run that validation we did earlier
                sh 'kubectl apply --dry-run=client -f project-1/deployment.yaml'
            }
        }

        stage('Build Image') {
            steps {
                echo "Building Docker Image: ${DOCKER_IMAGE}:${DOCKER_TAG}"
                sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
            }
        }

        stage('Deploy to K8s') {
            steps {
                echo 'Deploying to Local Cluster...'
                sh "kubectl apply -f deployment.yaml"
                sh "kubectl rollout status deployment/chaos-app"
            }
        }
    }
}
